language: cpp
compiler:
      - clang
      - gcc
before_script:
    - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz && tar xf lcov_1.11.orig.tar.gz &&  sudo make -C lcov-1.11/ install 2>&1 >/dev/null
    - sudo pip install cpp-coveralls 2>&1 >/dev/null
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 2>&1 >/dev/null; fi
    - sudo add-apt-repository -y ppa:boost-latest/ppa  2>&1 >/dev/null
    - sudo apt-get update -qq 2>&1 >/dev/null
    - sudo apt-get install -qq boost1.55 lua5.2 liblua5.2-dev 2>&1 >/dev/null
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8; fi
    - autoreconf -i
script: ./configure --enable-gcov && make test
after_success:
      - coveralls --exclude lib --gcov-options '\-lp'
